CREATE DATABASE laundry_data;
USE laundry_data;
CREATE TABLE scrape(id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, scrape_ts TIMESTAMP NOT NULL DEFAULT now(), washing TINYINT UNSIGNED NOT NULL, dryer TINYINT UNSIGNED NOT NULL);